# Generated by Django 5.0 on 2023-12-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
